/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../main';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '../../../src/ng-lock-system.module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/core/src/application_init';
import * as import8 from '@angular/core/src/testability/testability';
import * as import9 from '@angular/core/src/application_ref';
import * as import10 from '@angular/core/src/linker/compiler';
import * as import11 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import12 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import13 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import14 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import15 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import16 from '@angular/core/src/animation/animation_queue';
import * as import17 from '@angular/core/src/linker/view_utils';
import * as import18 from '@angular/platform-browser/src/browser/title';
import * as import19 from '../../../src/util.service';
import * as import20 from '../../../src/lock-manager.service';
import * as import21 from '@angular/core/src/di/injector';
import * as import22 from '@angular/core/src/i18n/tokens';
import * as import23 from '@angular/core/src/application_tokens';
import * as import24 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import25 from '@angular/platform-browser/src/dom/events/key_events';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import28 from '@angular/core/src/console';
import * as import29 from '@angular/core/src/error_handler';
import * as import30 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import31 from '@angular/platform-browser/src/dom/animation_driver';
import * as import32 from '@angular/core/src/render/api';
import * as import33 from '@angular/core/src/security';
import * as import34 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import35 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import36 from '@angular/core/src/linker/view';
import * as import37 from '@angular/core/src/metadata/view';
import * as import38 from '@angular/core/src/linker/view_type';
import * as import39 from '@angular/core/src/change_detection/constants';
import * as import40 from '@angular/core/src/linker/component_factory';
import * as import41 from '@angular/common/src/pipes/async_pipe';
import * as import42 from '@angular/core/src/change_detection/change_detection_util';
class NgcSpecModuleInjector extends import0.NgModuleInjector<import1.NgcSpecModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _NgLockSystemModule_3:import5.NgLockSystemModule;
  _NgcSpecModule_4:import1.NgcSpecModule;
  __LOCALE_ID_5:any;
  __NgLocalization_6:import6.NgLocaleLocalization;
  _ErrorHandler_7:any;
  _ApplicationInitStatus_8:import7.ApplicationInitStatus;
  _Testability_9:import8.Testability;
  _ApplicationRef__10:import9.ApplicationRef_;
  __ApplicationRef_11:any;
  __Compiler_12:import10.Compiler;
  __APP_ID_13:any;
  __DOCUMENT_14:any;
  __HAMMER_GESTURE_CONFIG_15:import11.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_16:any[];
  __EventManager_17:import12.EventManager;
  _DomSharedStylesHost_18:import13.DomSharedStylesHost;
  __AnimationDriver_19:any;
  __DomRootRenderer_20:import14.DomRootRenderer_;
  __RootRenderer_21:any;
  __DomSanitizer_22:import15.DomSanitizerImpl;
  __Sanitizer_23:any;
  __AnimationQueue_24:import16.AnimationQueue;
  __ViewUtils_25:import17.ViewUtils;
  __IterableDiffers_26:any;
  __KeyValueDiffers_27:any;
  __SharedStylesHost_28:any;
  __Title_29:import18.Title;
  __UtilService_30:import19.UtilService;
  _ENABLE_LOGGING_31:any;
  _LockManagerService_32:import20.LockManagerService;
  constructor(parent:import21.Injector) {
    super(parent,[NgcSpecComponentNgFactory],[NgcSpecComponentNgFactory]);
  }
  get _LOCALE_ID_5():any {
    if ((this.__LOCALE_ID_5 == null)) { (this.__LOCALE_ID_5 = import3._localeFactory(this.parent.get(import22.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_5;
  }
  get _NgLocalization_6():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import6.NgLocaleLocalization(this._LOCALE_ID_5)); }
    return this.__NgLocalization_6;
  }
  get _ApplicationRef_11():any {
    if ((this.__ApplicationRef_11 == null)) { (this.__ApplicationRef_11 = this._ApplicationRef__10); }
    return this.__ApplicationRef_11;
  }
  get _Compiler_12():import10.Compiler {
    if ((this.__Compiler_12 == null)) { (this.__Compiler_12 = new import10.Compiler()); }
    return this.__Compiler_12;
  }
  get _APP_ID_13():any {
    if ((this.__APP_ID_13 == null)) { (this.__APP_ID_13 = import23._appIdRandomProviderFactory()); }
    return this.__APP_ID_13;
  }
  get _DOCUMENT_14():any {
    if ((this.__DOCUMENT_14 == null)) { (this.__DOCUMENT_14 = import4._document()); }
    return this.__DOCUMENT_14;
  }
  get _HAMMER_GESTURE_CONFIG_15():import11.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_15 == null)) { (this.__HAMMER_GESTURE_CONFIG_15 = new import11.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_15;
  }
  get _EVENT_MANAGER_PLUGINS_16():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_16 == null)) { (this.__EVENT_MANAGER_PLUGINS_16 = [
      new import24.DomEventsPlugin(),
      new import25.KeyEventsPlugin(),
      new import11.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_15)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_16;
  }
  get _EventManager_17():import12.EventManager {
    if ((this.__EventManager_17 == null)) { (this.__EventManager_17 = new import12.EventManager(this._EVENT_MANAGER_PLUGINS_16,this.parent.get(import26.NgZone))); }
    return this.__EventManager_17;
  }
  get _AnimationDriver_19():any {
    if ((this.__AnimationDriver_19 == null)) { (this.__AnimationDriver_19 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_19;
  }
  get _DomRootRenderer_20():import14.DomRootRenderer_ {
    if ((this.__DomRootRenderer_20 == null)) { (this.__DomRootRenderer_20 = new import14.DomRootRenderer_(this._DOCUMENT_14,this._EventManager_17,this._DomSharedStylesHost_18,this._AnimationDriver_19,this._APP_ID_13)); }
    return this.__DomRootRenderer_20;
  }
  get _RootRenderer_21():any {
    if ((this.__RootRenderer_21 == null)) { (this.__RootRenderer_21 = import27._createConditionalRootRenderer(this._DomRootRenderer_20,this.parent.get(import27.NgProbeToken,(null as any)),this.parent.get(import9.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_21;
  }
  get _DomSanitizer_22():import15.DomSanitizerImpl {
    if ((this.__DomSanitizer_22 == null)) { (this.__DomSanitizer_22 = new import15.DomSanitizerImpl()); }
    return this.__DomSanitizer_22;
  }
  get _Sanitizer_23():any {
    if ((this.__Sanitizer_23 == null)) { (this.__Sanitizer_23 = this._DomSanitizer_22); }
    return this.__Sanitizer_23;
  }
  get _AnimationQueue_24():import16.AnimationQueue {
    if ((this.__AnimationQueue_24 == null)) { (this.__AnimationQueue_24 = new import16.AnimationQueue(this.parent.get(import26.NgZone))); }
    return this.__AnimationQueue_24;
  }
  get _ViewUtils_25():import17.ViewUtils {
    if ((this.__ViewUtils_25 == null)) { (this.__ViewUtils_25 = new import17.ViewUtils(this._RootRenderer_21,this._Sanitizer_23,this._AnimationQueue_24)); }
    return this.__ViewUtils_25;
  }
  get _IterableDiffers_26():any {
    if ((this.__IterableDiffers_26 == null)) { (this.__IterableDiffers_26 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_26;
  }
  get _KeyValueDiffers_27():any {
    if ((this.__KeyValueDiffers_27 == null)) { (this.__KeyValueDiffers_27 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_27;
  }
  get _SharedStylesHost_28():any {
    if ((this.__SharedStylesHost_28 == null)) { (this.__SharedStylesHost_28 = this._DomSharedStylesHost_18); }
    return this.__SharedStylesHost_28;
  }
  get _Title_29():import18.Title {
    if ((this.__Title_29 == null)) { (this.__Title_29 = new import18.Title()); }
    return this.__Title_29;
  }
  get _UtilService_30():import19.UtilService {
    if ((this.__UtilService_30 == null)) { (this.__UtilService_30 = new import19.UtilService()); }
    return this.__UtilService_30;
  }
  createInternal():import1.NgcSpecModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._NgLockSystemModule_3 = new import5.NgLockSystemModule(this);
    this._NgcSpecModule_4 = new import1.NgcSpecModule();
    this._ErrorHandler_7 = import4.errorHandler();
    this._ApplicationInitStatus_8 = new import7.ApplicationInitStatus(this.parent.get(import7.APP_INITIALIZER,(null as any)));
    this._Testability_9 = new import8.Testability(this.parent.get(import26.NgZone));
    this._ApplicationRef__10 = new import9.ApplicationRef_(this.parent.get(import26.NgZone),this.parent.get(import28.Console),this,this._ErrorHandler_7,this,this._ApplicationInitStatus_8,this.parent.get(import8.TestabilityRegistry,(null as any)),this._Testability_9);
    this._DomSharedStylesHost_18 = new import13.DomSharedStylesHost(this._DOCUMENT_14);
    this._ENABLE_LOGGING_31 = true;
    this._LockManagerService_32 = new import20.LockManagerService(this._ENABLE_LOGGING_31,this._UtilService_30);
    return this._NgcSpecModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.NgLockSystemModule)) { return this._NgLockSystemModule_3; }
    if ((token === import1.NgcSpecModule)) { return this._NgcSpecModule_4; }
    if ((token === import22.LOCALE_ID)) { return this._LOCALE_ID_5; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import29.ErrorHandler)) { return this._ErrorHandler_7; }
    if ((token === import7.ApplicationInitStatus)) { return this._ApplicationInitStatus_8; }
    if ((token === import8.Testability)) { return this._Testability_9; }
    if ((token === import9.ApplicationRef_)) { return this._ApplicationRef__10; }
    if ((token === import9.ApplicationRef)) { return this._ApplicationRef_11; }
    if ((token === import10.Compiler)) { return this._Compiler_12; }
    if ((token === import23.APP_ID)) { return this._APP_ID_13; }
    if ((token === import30.DOCUMENT)) { return this._DOCUMENT_14; }
    if ((token === import11.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_15; }
    if ((token === import12.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_16; }
    if ((token === import12.EventManager)) { return this._EventManager_17; }
    if ((token === import13.DomSharedStylesHost)) { return this._DomSharedStylesHost_18; }
    if ((token === import31.AnimationDriver)) { return this._AnimationDriver_19; }
    if ((token === import14.DomRootRenderer)) { return this._DomRootRenderer_20; }
    if ((token === import32.RootRenderer)) { return this._RootRenderer_21; }
    if ((token === import15.DomSanitizer)) { return this._DomSanitizer_22; }
    if ((token === import33.Sanitizer)) { return this._Sanitizer_23; }
    if ((token === import16.AnimationQueue)) { return this._AnimationQueue_24; }
    if ((token === import17.ViewUtils)) { return this._ViewUtils_25; }
    if ((token === import34.IterableDiffers)) { return this._IterableDiffers_26; }
    if ((token === import35.KeyValueDiffers)) { return this._KeyValueDiffers_27; }
    if ((token === import13.SharedStylesHost)) { return this._SharedStylesHost_28; }
    if ((token === import18.Title)) { return this._Title_29; }
    if ((token === import19.UtilService)) { return this._UtilService_30; }
    if ((token === import5.ENABLE_LOGGING)) { return this._ENABLE_LOGGING_31; }
    if ((token === import20.LockManagerService)) { return this._LockManagerService_32; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__10.ngOnDestroy();
    this._DomSharedStylesHost_18.ngOnDestroy();
    this._LockManagerService_32.ngOnDestroy();
  }
}
export const NgcSpecModuleNgFactory:import0.NgModuleFactory<import1.NgcSpecModule> = new import0.NgModuleFactory(NgcSpecModuleInjector,import1.NgcSpecModule);
export class Wrapper_NgcSpecComponent {
  /*private*/ _eventHandler:Function;
  context:import1.NgcSpecComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import1.NgcSpecComponent();
  }
  ngOnDetach(view:import36.AppView<any>,componentView:import36.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import36.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import36.AppView<any>,componentView:import36.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import36.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_NgcSpecComponent_Host:import32.RenderComponentType = import17.createRenderComponentType('',0,import37.ViewEncapsulation.None,([] as any[]),{});
class View_NgcSpecComponent_Host0 extends import36.AppView<any> {
  _el_0:any;
  compView_0:import36.AppView<import1.NgcSpecComponent>;
  _NgcSpecComponent_0_3:Wrapper_NgcSpecComponent;
  constructor(viewUtils:import17.ViewUtils,parentView:import36.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NgcSpecComponent_Host0,renderType_NgcSpecComponent_Host,import38.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import39.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import40.ComponentRef<any> {
    this._el_0 = import17.selectOrCreateRenderHostElement(this.renderer,'ngc-spec-component',import17.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_NgcSpecComponent0(this.viewUtils,this,0,this._el_0);
    this._NgcSpecComponent_0_3 = new Wrapper_NgcSpecComponent();
    this.compView_0.create(this._NgcSpecComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import40.ComponentRef_<any>(0,this,this._el_0,this._NgcSpecComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.NgcSpecComponent) && (0 === requestNodeIndex))) { return this._NgcSpecComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgcSpecComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const NgcSpecComponentNgFactory:import40.ComponentFactory<import1.NgcSpecComponent> = new import40.ComponentFactory<import1.NgcSpecComponent>('ngc-spec-component',View_NgcSpecComponent_Host0,import1.NgcSpecComponent);
const styles_NgcSpecComponent:any[] = ([] as any[]);
var renderType_NgcSpecComponent:import32.RenderComponentType = import17.createRenderComponentType('',0,import37.ViewEncapsulation.None,styles_NgcSpecComponent,{});
export class View_NgcSpecComponent0 extends import36.AppView<import1.NgcSpecComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_9:any;
  _pipe_async_0:import41.AsyncPipe;
  constructor(viewUtils:import17.ViewUtils,parentView:import36.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NgcSpecComponent0,renderType_NgcSpecComponent,import38.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import39.ChangeDetectorStatus.CheckAlways);
    this._expr_9 = import42.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import40.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import17.createRenderElement(this.renderer,parentRenderNode,'div',import17.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_3 = import17.createRenderElement(this.renderer,parentRenderNode,'button',new import17.InlineArray2(2,'click','lock()'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Lock',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_6 = import17.createRenderElement(this.renderer,parentRenderNode,'button',new import17.InlineArray2(2,'click','unlock()'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Unlock',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._pipe_async_0 = new import41.AsyncPipe(this.ref);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import42.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_9:any = (valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.isLocked$))? 'red': 'black');
    if ((valUnwrapper.hasWrappedValue || import17.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setElementStyle(this._el_1,'background-color',((this.viewUtils.sanitizer.sanitize(import33.SecurityContext.STYLE,currVal_9) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import33.SecurityContext.STYLE,currVal_9).toString()));
      this._expr_9 = currVal_9;
    }
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}