/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng-lock-system.module';
import * as import2 from '@angular/core/src/di/injector';
class NgLockSystemModuleInjector extends import0.NgModuleInjector<import1.NgLockSystemModule> {
  _NgLockSystemModule_0:import1.NgLockSystemModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.NgLockSystemModule {
    this._NgLockSystemModule_0 = new import1.NgLockSystemModule(this);
    return this._NgLockSystemModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.NgLockSystemModule)) { return this._NgLockSystemModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgLockSystemModuleNgFactory:import0.NgModuleFactory<import1.NgLockSystemModule> = new import0.NgModuleFactory(NgLockSystemModuleInjector,import1.NgLockSystemModule);